### ISSUE TITLE
即使是有难度也应该开源啊

### ISSUE THREAD

**Issue by luanluanxu** [kalcaddle/KodExplorer#381]
大家都是开发者，再怎么有难度也难不倒我们，这已经不算是开源了，没办法自己二开

**Comment by chaosye0** [comment]
都出商用了怎么可能给你完全开源。。。

**Comment by kalcaddle** [comment]
感谢支持。
从业余到组建团队开发，有一个过程。新版全面重构，即将发布，免费会永久保留，迫于盗版售卖压力还是采用部分来源。后续会逐步开源。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chaosye0 <notifications@github.com&gt;
发送时间: 2019年10月13日 12:16
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 即使是有难度也应该开源啊 (#381)




都出商用了怎么可能给你完全开源。。。

**Comment by lujiaxing** [comment]
> 感谢支持。 从业余到组建团队开发，有一个过程。新版全面重构，即将发布，免费会永久保留，迫于盗版售卖压力还是采用部分来源。后续会逐步开源。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: chaosye0 <notifications@github.com&gt; 发送时间: 2019年10月13日 12:16 收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[kalcaddle/KodExplorer] 即使是有难度也应该开源啊 (#381) 都出商用了怎么可能给你完全开源。。。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

但是你们用的是 GPL v3 协议, 根据 GPL 协议传染性的特性, 你们所有源码必须是无条件 100% 开放的. 不存在 "部分开源" 的说法. 而且所有与核心模块存在直接引用调用的部分的源码也必须是开源的.

至于未来你们可以参照 TinyMCE 的做法: 核心功能开源, 插件收费.

**Comment by pch18** [comment]
别理这种人，支持官方的做法，再说单纯php又不是编译后发布的，不存在不开源，只有混淆加密。那也算是公开源码，你们自己能力不足看不懂怪谁。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 阿星～ <notifications@github.com&gt;
发送时间: 2019年11月21日 16:18
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] 即使是有难度也应该开源啊 (#381)



 
感谢支持。 从业余到组建团队开发，有一个过程。新版全面重构，即将发布，免费会永久保留，迫于盗版售卖压力还是采用部分来源。后续会逐步开源。 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: chaosye0 <notifications@github.com&gt; 发送时间: 2019年10月13日 12:16 收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[kalcaddle/KodExplorer] 即使是有难度也应该开源啊 (#381) 都出商用了怎么可能给你完全开源。。。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
但是你们用的是 GPL v3 协议, 根据 GPL 协议传染性的特性, 你们所有源码必须是无条件 100% 开放的. 不存在 "部分开源" 的说法. 而且所有与核心模块存在直接引用调用的部分的源码也必须是开源的.
 
至于未来你们可以参照 TinyMCE 的做法: 核心功能开源, 插件收费.
