### ISSUE TITLE
Which version is open-source?   哪个版本是开源的？

### ISSUE THREAD

**Issue by githubetc** [kalcaddle/KodExplorer#393]
Thanks for releasing your software as open source.
On the https://github.com/kalcaddle/KodExplorer page, you said the license is GPLv3.
On your website https://kodcloud.com/price/ there are many different versions.
Can you please tell us which version is on github ?
The github version supports how many users ?

谢谢您将软件发布为开源软件。
在 https://github.com/kalcaddle/KodExplorer 页上，您说许可证是GPLv3。
在您的网站 https://kodcloud.com/price/ 上，有不同的版本。
请问 github 上的是哪个版本？
github 上的版本支持的用户数量是多少？

**Comment by pch18** [comment]
替官方回答你，所有版本都是同一个版本，通过不同序列号开启相应功能。

**Comment by githubetc** [comment]
Thanks very much for your reply.
Even for the github version, I will still need to purchase serial number in order to unlock extra features ?

非常感谢您的回复。
即使是github版本，我仍然需要购买序列号才能解锁其他功能？

**Comment by kalcaddle** [comment]
yes,you are right



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: githubetc <notifications@github.com&gt;
发送时间: 2019年12月24日 09:46
收件人: kalcaddle/KodExplorer <KodExplorer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[kalcaddle/KodExplorer] Which version is open-source?   哪个版本是开源的？ (#393)




Thanks very much for your reply.
Even for the github version, I will still need to purchase serial number in order to unlock extra features ?

非常感谢您的回复。
即使是github版本，我仍然需要购买序列号才能解锁其他功能？
